use std::path::Path;
use tokio::fs::File;
use tokio::io::AsyncWriteExt;
use crate::error::MsbError;

/// EULA（使用許諾契約）ファイルを作成します。
/// 
/// @param dir ファイルを作成するディレクトリのパス
/// @param accepted EULAに同意するかどうか
/// @requires 指定されたディレクトリが書き込み可能であること
/// @return 成功した場合はOk(()), 失敗した場合はMsbError
pub async fn create_eula_file(dir: &Path, accepted: bool) -> Result<(), MsbError> {
    let eula_path = dir.join("eula.txt");
    let content = format!(
        "#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).\n#Generated by MSB\neula={}\n",
        accepted
    );
    let mut file = File::create(eula_path).await?;
    file.write_all(content.as_bytes()).await?;
    Ok(())
}
